const kataMotivasi = [
    "Kata-kata untuk {nama}, ngapain sok sibuk? Hidup lu juga gitu-gitu aja.",
    "Kata-kata untuk {nama}, udah lah, berhenti berusaha. Nggak bakal ada yang peduli juga.",
    "Kata-kata untuk {nama}, capek-capek kerja keras? Hasilnya paling juga sampah.",
    "Kata-kata untuk {nama}, hidup itu nggak akan lebih baik. Mending pasrah aja.",
    "Kata-kata untuk {nama}, mimpi lu cuma omong kosong, mending rebahan aja.",
    "Kata-kata untuk {nama}, buat apa sok sibuk? Nggak ada yang akan ingat lu juga.",
    "Kata-kata untuk {nama}, nggak usah mimpi tinggi-tinggi, ntar jatuh makin sakit.",
    "Kata-kata untuk {nama}, hidup lu nggak akan berubah, jadi mending diem aja.",
    "Kata-kata untuk {nama}, kenapa lu masih usaha? Toh ujung-ujungnya gagal juga.",
    "Kata-kata untuk {nama}, hidup lu cuma sekali dan nggak ada yang peduli.",
    "Kata-kata untuk {nama}, ngapain capek-capek? Toh hasilnya nggak bakal signifikan.",
    "Kata-kata untuk {nama}, buat apa lu berusaha? Semua orang juga tahu lu bakal gagal.",
    "Kata-kata untuk {nama}, percuma lu kerja keras, hidup lu tetap nggak ada artinya.",
    "Kata-kata untuk {nama}, lu pikir usaha lu berarti? Orang lain bahkan nggak lihat.",
    "Kata-kata untuk {nama}, mending lu nyerah aja, karena hasilnya pasti payah.",
    "Kata-kata untuk {nama}, buat apa mikir panjang? Hidup lu nggak akan kemana-mana.",
    "Kata-kata untuk {nama}, percuma lu ngoyo, ending-nya tetap zonk.",
    "Kata-kata untuk {nama}, ngapain lu pusing-pusing? Hidup lu nggak bakal berubah.",
    "Kata-kata untuk {nama}, stop berharap, hidup lu cuma sebatas itu.",
    "Kata-kata untuk {nama}, lu nggak usah capek-capek. Hidup lu udah mentok.",
    "Kata-kata untuk {nama}, nggak usah repot-repot, nggak ada yang peduli sama lu.",
    "Kata-kata untuk {nama}, usaha lu sia-sia, nggak akan ada yang berubah.",
    "Kata-kata untuk {nama}, ngapain lu sok ambisius? Nggak bakal ada yang bangga sama lu.",
    "Kata-kata untuk {nama}, buat apa berjuang? Orang lain juga nggak peduli.",
    "Kata-kata untuk {nama}, mending diem aja, setiap langkah lu salah.",
    "Kata-kata untuk {nama}, lu nggak usah mimpi besar, nanti cuma sakit hati.",
    "Kata-kata untuk {nama}, hidup itu kejam, dan lu nggak bakal menang.",
    "Kata-kata untuk {nama}, jangan terlalu berharap, nanti lu kecewa banget.",
    "Kata-kata untuk {nama}, ngapain mimpi tinggi? Ntar jatuh makin keras.",
    "Kata-kata untuk {nama}, nggak usah sok kuat, semua orang tahu lu lemah.",
    "Kata-kata untuk {nama}, buat apa lu capek-capek? Toh, hasilnya nggak ada yang peduli.",
    "Kata-kata untuk {nama}, lu cuma buang-buang waktu, hidup lu udah nggak ada harapan.",
    "Kata-kata untuk {nama}, berhenti berharap, karena nggak ada yang peduli sama lu.",
    "Kata-kata untuk {nama}, mimpi lu ketinggian, nanti lu jatuh sakit sendiri.",
    "Kata-kata untuk {nama}, ngapain lu sok ambisius? Toh, lu nggak akan ke mana-mana.",
    "Kata-kata untuk {nama}, hidup lu gitu-gitu aja, mending diem daripada nyusahin diri.",
    "Kata-kata untuk {nama}, buat apa lu repot-repot? Hidup lu cuma sia-sia.",
    "Kata-kata untuk {nama}, percuma lu mikir keras, hasilnya tetap bakal nol.",
    "Kata-kata untuk {nama}, berhenti sok sibuk, lu nggak ada yang bakal ingat.",
    "Kata-kata untuk {nama}, mimpi lu cuma buang-buang waktu, mending rebahan.",
    "Kata-kata untuk {nama}, ngapain lu usaha? Ujung-ujungnya juga bakal gagal.",
    "Kata-kata untuk {nama}, nggak usah capek-capek, hasilnya nggak akan beda.",
    "Kata-kata untuk {nama}, buat apa lu berusaha? Semua orang tahu lu nggak bakal sukses.",
    "Kata-kata untuk {nama}, lu nggak akan pernah cukup baik, jadi mending berhenti.",
    "Kata-kata untuk {nama}, nggak ada gunanya mimpi, kenyataan lu terlalu buruk.",
    "Kata-kata untuk {nama}, hidup lu cuma mimpi buruk, jadi mending jangan berharap.",
    "Kata-kata untuk {nama}, ngapain lu pusing? Hidup lu nggak akan kemana-mana.",
    "Kata-kata untuk {nama}, stop usaha, hidup lu udah berakhir di sini.",
    "Kata-kata untuk {nama}, ngapain repot? Toh, semua bakal lupa sama lu.",
    "Kata-kata untuk {nama}, buat apa sok sibuk? Lu nggak akan pernah mencapai apa-apa."
];


const nama = [
    "Adam", "Ade", "Upho", "Bunga", "Ainun", "Madun", "Bagus", "Bayu", "Bintang",
    "Aji", "Endri", "Salim", "Baim", "Ivana", "Jajang", "Irul", "Leo", "Ali",
    "Naufal", "Farhan", "Nurul", "Ikbal", "Iza", "Rafi", "Alam", "Rama", "Iky",
    "Timothi", "Yohan", "Doy", "Afari", "Adit", "Very", "Dhea", "Elsa", "Wisnu", "Ammar", "Riska", "Nanda", "Baqir"
];
const kataKakGem = [
    "Kata-kata hari ini, Tetap semangat, perjalanan panjang dimulai dari langkah kecil.",
    "Kata-kata hari ini, Jangan menyerah, kesuksesan membutuhkan ketekunan.",
    "Kata-kata hari ini, Setiap tantangan adalah peluang untuk belajar.",
    "Kata-kata hari ini, Kamu lebih kuat dari yang kamu kira.",
    "Kata-kata hari ini, Mimpi besar dimulai dari usaha kecil.",
    "Kata-kata hari ini, Keberhasilan adalah hasil dari kerja keras dan dedikasi.",
    "Kata-kata hari ini, Hari ini adalah kesempatan untuk menjadi lebih baik dari kemarin.",
    "Kata-kata hari ini, Berani mencoba adalah awal dari kesuksesan.",
    "Kata-kata hari ini, Kegagalan adalah batu loncatan menuju keberhasilan.",
    "Kata-kata hari ini, Setiap hari adalah halaman baru dalam kisah hidupmu.",
    "Kata-kata hari ini, Teruslah bergerak maju, langkah kecil pun akan membawa ke tujuan.",
    "Kata-kata hari ini, Peluang besar sering kali tersembunyi di balik tantangan yang sulit.",
    "Kata-kata hari ini, Jadilah versi terbaik dari dirimu setiap hari.",
    "Kata-kata hari ini, Waktu tidak akan menunggu, manfaatkan setiap detiknya.",
    "Kata-kata hari ini, Kesuksesan tidak datang dengan sendirinya, tapi dengan usaha yang tak kenal lelah.",
    "Kata-kata hari ini, Setiap orang sukses pernah gagal, yang penting adalah bangkit lagi.",
    "Kata-kata hari ini, Bekerjalah dengan hati, hasilnya akan mengikuti.",
    "Kata-kata hari ini, Percayalah pada proses, hasilnya akan datang.",
    "Kata-kata hari ini, Setiap langkah yang diambil, sejauh apapun itu, mendekatkanmu ke tujuan.",
    "Kata-kata hari ini, Tidak ada yang mustahil jika kamu memiliki tekad yang kuat.",
    "Kata-kata hari ini, Kesabaran dan ketekunan adalah kunci keberhasilan.",
    "Kata-kata hari ini, Tidak ada yang mudah, tapi semua bisa dicapai dengan kerja keras.",
    "Kata-kata hari ini, Berpikir positif adalah langkah pertama menuju sukses.",
    "Kata-kata hari ini, Keberanian untuk memulai adalah awal dari segala sesuatu yang hebat.",
    "Kata-kata hari ini, Masa depanmu ditentukan oleh apa yang kamu lakukan hari ini.",
    "Kata-kata hari ini, Kegagalan adalah bagian dari perjalanan menuju sukses.",
    "Kata-kata hari ini, Belajarlah dari setiap kesalahan, dan jadilah lebih baik.",
    "Kata-kata hari ini, Hidup ini penuh dengan kesempatan, jangan sia-siakan.",
    "Kata-kata hari ini, Jangan takut mencoba, karena kegagalan adalah guru terbaik.",
    "Kata-kata hari ini, Hanya mereka yang berani gagal yang bisa meraih kesuksesan besar.",
    "Kata-kata hari ini, Kesuksesan tidak datang kepada mereka yang hanya menunggu.",
    "Kata-kata hari ini, Setiap hari adalah kesempatan baru untuk meraih impianmu.",
    "Kata-kata hari ini, Bersyukurlah untuk setiap tantangan, karena itu membuatmu lebih kuat.",
    "Kata-kata hari ini, Jangan biarkan rasa takut menghentikan langkahmu.",
    "Kata-kata hari ini, Fokuslah pada tujuanmu, bukan pada rintangan yang menghadang.",
    "Kata-kata hari ini, Setiap usaha yang tulus akan membuahkan hasil.",
    "Kata-kata hari ini, Kesuksesan adalah hasil dari persiapan, kerja keras, dan belajar dari kegagalan.",
    "Kata-kata hari ini, Beranilah untuk bermimpi besar dan bekerja keras untuk mencapainya.",
    "Kata-kata hari ini, Ketekunan adalah bahan bakar dari kesuksesan.",
    "Kata-kata hari ini, Tetaplah rendah hati dalam kesuksesan dan kuat dalam kesulitan.",
    "Kata-kata hari ini, Hidup ini tentang perjalanan, bukan tentang tujuan akhir.",
    "Kata-kata hari ini, Jangan pernah berhenti belajar, karena hidup tidak pernah berhenti mengajar.",
    "Kata-kata hari ini, Setiap orang memiliki waktu yang sama, gunakanlah dengan bijak.",
    "Kata-kata hari ini, Kerjakan apa yang bisa kamu kerjakan hari ini, jangan menunggu esok.",
    "Kata-kata hari ini, Impianmu menunggu di sisi lain dari ketakutanmu.",
    "Kata-kata hari ini, Jangan biarkan masa lalu menahanmu dari meraih masa depan.",
    "Kata-kata hari ini, Kamu tidak pernah tahu seberapa dekatnya kesuksesan jika kamu menyerah.",
    "Kata-kata hari ini, Percayalah bahwa kamu bisa, dan kamu sudah setengah jalan ke sana.",
    "Kata-kata hari ini, Kebahagiaan tidak ditemukan di ujung jalan, tapi di sepanjang perjalanan."
];

<<<<<<< HEAD
const kataJorok = ['anjing', 'kontol', 'memek', 'bangsat', 'tai', 'ngentot', 'ngentod', 'babi', 'asu', 'fak', 'fuck', 'puki', 'cuki', 'pepek', 'bokep',
'ktl','ppk','anj','mampus','ewe','bgst','anying','mmk','anjir','ajg','ewean','mamfus','peler','titit','itil','k0nt0l','kuontol',
'k0ntol','kont0l','memeg','memex','muemek'];


module.exports = { kataMotivasi, nama, kataKakGem, kataJorok };
=======

module.exports = { kataMotivasi, nama, kataKakGem };
>>>>>>> a7728c0f2b860168002751faa763ecafc73aec24
