const kataMotivasi = [
    "Hai {nama}, santai aja, jangan terlalu keras pada diri sendiri. Hidup itu proses, nikmati aja.",
    "Untuk {nama}, mungkin sekarang berat, tapi setiap usaha kamu itu berharga. Terus berjuang, ya.",
    "Hei {nama}, kamu udah sejauh ini, jangan berhenti sekarang. Hasil besar butuh waktu.",
    "Halo {nama}, kadang hidup memang nggak mudah, tapi kamu lebih kuat dari yang kamu kira.",
    "Hey {nama}, setiap mimpi itu penting, jangan biarkan rasa takut menghentikan langkahmu.",
    "Buat {nama}, mungkin nggak ada yang lihat usahamu sekarang, tapi suatu saat dunia akan tahu.",
    "Untuk {nama}, setinggi apapun mimpi kamu, tetaplah percaya, karena kamu layak mendapatkannya.",
    "Halo {nama}, hidup bisa berubah kapan saja. Tetaplah bergerak maju, sesuatu yang indah menantimu.",
    "Hai {nama}, mungkin sekarang terasa sulit, tapi percayalah, setiap usaha tidak ada yang sia-sia.",
    "Untuk {nama}, hidup memang cuma sekali, jadi buatlah setiap momen berharga.",
    "Hai {nama}, jangan menyerah. Setiap langkah kecil yang kamu ambil mendekatkanmu ke tujuan besar.",
    "Untuk {nama}, ingat, setiap kegagalan hanya membawa kamu lebih dekat pada keberhasilan.",
    "Hai {nama}, usaha kamu berarti lebih dari yang kamu bayangkan. Terus maju dan lihatlah hasilnya nanti.",
    "Untuk {nama}, kamu nggak perlu sempurna. Yang penting kamu terus mencoba dan belajar.",
    "Hai {nama}, mungkin sekarang terasa berat, tapi jangan lupa, badai pasti berlalu.",
    "Untuk {nama}, jangan takut bermimpi besar. Karena dari mimpi besar, lahir pencapaian besar.",
    "Hei {nama}, setiap orang punya perjalanan sendiri, dan perjalanan kamu pasti membawa ke tempat yang luar biasa.",
    "Hai {nama}, setiap usaha yang kamu lakukan akan memberikan pelajaran berharga, jadi teruslah melangkah.",
    "Untuk {nama}, jangan takut gagal. Setiap kesalahan adalah langkah menuju kesuksesan.",
    "Hei {nama}, jangan berhenti di tengah jalan. Kamu nggak akan tahu seberapa dekat kamu dengan impianmu.",
    "Halo {nama}, jangan khawatir kalau belum terlihat hasilnya. Hasil besar membutuhkan waktu.",
    "Hei {nama}, mungkin nggak semua orang mengerti perjuangan kamu, tapi kamu harus tetap percaya pada dirimu sendiri.",
    "Hai {nama}, mungkin orang lain nggak melihat usahamu, tapi yang penting kamu melangkah untuk dirimu sendiri.",
    "Untuk {nama}, teruslah berjuang, karena pada akhirnya semua usaha akan terbayar.",
    "Hai {nama}, hidup memang penuh tantangan, tapi kamu punya kekuatan untuk mengatasinya.",
    "Hei {nama}, mimpi kamu mungkin besar, tapi kamu juga punya kemampuan untuk mencapainya.",
    "Hai {nama}, kadang yang dibutuhkan hanya kesabaran. Semua akan indah pada waktunya.",
    "Halo {nama}, jangan biarkan rintangan kecil menghentikan langkahmu menuju tujuan besar.",
    "Untuk {nama}, selalu ada harapan, selama kamu tidak berhenti percaya dan berusaha.",
    "Hei {nama}, kamu lebih kuat dari yang kamu kira. Jangan biarkan satu kegagalan menghentikanmu.",
    "Hai {nama}, percayalah, setiap usaha yang kamu lakukan punya arti penting.",
    "Untuk {nama}, hidup mungkin penuh tantangan, tapi kamu pasti bisa melewatinya dengan kuat.",
    "Hei {nama}, jangan takut bermimpi besar. Karena dari mimpi besar, pencapaian luar biasa dimulai.",
    "Halo {nama}, mimpi kamu nggak terlalu tinggi. Kamu hanya perlu terus melangkah untuk mencapainya.",
    "Untuk {nama}, jangan biarkan rasa takut menghentikanmu. Setiap langkah maju adalah kemenangan.",
    "Hai {nama}, kamu lebih berharga dari apa yang kamu pikirkan. Teruslah berusaha, jangan menyerah.",
    "Hei {nama}, jangan ragu untuk terus mencoba. Karena setiap kali kamu mencoba, kamu semakin dekat dengan sukses.",
    "Hai {nama}, mungkin hari ini berat, tapi ingatlah, badai pasti berlalu.",
    "Untuk {nama}, hasil besar nggak terjadi dalam semalam. Tapi setiap langkah kecilmu membawa perubahan besar.",
    "Halo {nama}, mungkin sekarang terasa sulit, tapi percayalah, semua akan terbayar suatu hari nanti.",
    "Hei {nama}, jangan takut gagal. Setiap kegagalan membawa kamu lebih dekat ke kesuksesan.",
    "Hai {nama}, teruslah bermimpi dan bekerja keras. Suatu saat, mimpimu akan menjadi nyata.",
    "Untuk {nama}, setiap mimpi besar dimulai dari langkah kecil. Teruslah melangkah.",
    "Hai {nama}, jangan takut mencoba hal baru. Karena dari percobaan baru, kamu menemukan kesempatan baru.",
    "Hei {nama}, kamu nggak pernah tahu seberapa dekat kamu dengan sukses. Jadi jangan berhenti sekarang.",
    "Untuk {nama}, percayalah, setiap usaha yang kamu lakukan membawa kamu lebih dekat pada tujuanmu.",
    "Hai {nama}, kamu punya potensi luar biasa. Teruslah percaya pada diri sendiri.",
    "Hei {nama}, jangan biarkan kegagalan membuatmu mundur. Teruslah berjuang, sukses menantimu di depan sana."
];

const nama = [
    "Adam", "Ade", "Upho", "Bunga", "Ainun", "Madun", "Bagus", "Bayu", "Bintang",
    "Aji", "Endri", "Salim", "Baim", "Ivana", "Jajang", "Irul", "Leo", "Ali",
    "Naufal", "Farhan", "Nurul", "Ikbal", "Iza", "Rafi", "Alam", "Rama", "Iky",
    "Timothi", "Yohan", "Doy", "Afari", "Adit", "Very", "Dhea", "Elsa", "Wisnu", "Ammar", "Riska", "Baqir", "Khansa"
];

const emotBinatang  = [
    "🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷", "🐸", "🐵", "🐔", "🐧", "🐦", "🐤", "🦆", "🦉", "🦇", "🐺", "🐗", 
    "🐴", "🦄", "🐝", "🐛", "🦋", "🐌", "🐞", "🐜", "🦟", "🦗", "🐢", "🐍", "🦎", "🦂", "🦀", "🐡", "🐠", "🐟", "🐬", "🐳", "🦈", "🐊", "🐅", "🐆"
];

const kataKakGem = [
    "Kata-kata hari ini, Tetap semangat, perjalanan panjang dimulai dari langkah kecil.",
    "Kata-kata hari ini, Jangan menyerah, kesuksesan membutuhkan ketekunan.",
    "Kata-kata hari ini, Setiap tantangan adalah peluang untuk belajar.",
    "Kata-kata hari ini, Kamu lebih kuat dari yang kamu kira.",
    "Kata-kata hari ini, Mimpi besar dimulai dari usaha kecil.",
    "Kata-kata hari ini, Keberhasilan adalah hasil dari kerja keras dan dedikasi.",
    "Kata-kata hari ini, Hari ini adalah kesempatan untuk menjadi lebih baik dari kemarin.",
    "Kata-kata hari ini, Berani mencoba adalah awal dari kesuksesan.",
    "Kata-kata hari ini, Kegagalan adalah batu loncatan menuju keberhasilan.",
    "Kata-kata hari ini, Setiap hari adalah halaman baru dalam kisah hidupmu.",
    "Kata-kata hari ini, Teruslah bergerak maju, langkah kecil pun akan membawa ke tujuan.",
    "Kata-kata hari ini, Peluang besar sering kali tersembunyi di balik tantangan yang sulit.",
    "Kata-kata hari ini, Jadilah versi terbaik dari dirimu setiap hari.",
    "Kata-kata hari ini, Waktu tidak akan menunggu, manfaatkan setiap detiknya.",
    "Kata-kata hari ini, Kesuksesan tidak datang dengan sendirinya, tapi dengan usaha yang tak kenal lelah.",
    "Kata-kata hari ini, Setiap orang sukses pernah gagal, yang penting adalah bangkit lagi.",
    "Kata-kata hari ini, Bekerjalah dengan hati, hasilnya akan mengikuti.",
    "Kata-kata hari ini, Percayalah pada proses, hasilnya akan datang.",
    "Kata-kata hari ini, Setiap langkah yang diambil, sejauh apapun itu, mendekatkanmu ke tujuan.",
    "Kata-kata hari ini, Tidak ada yang mustahil jika kamu memiliki tekad yang kuat.",
    "Kata-kata hari ini, Kesabaran dan ketekunan adalah kunci keberhasilan.",
    "Kata-kata hari ini, Tidak ada yang mudah, tapi semua bisa dicapai dengan kerja keras.",
    "Kata-kata hari ini, Berpikir positif adalah langkah pertama menuju sukses.",
    "Kata-kata hari ini, Keberanian untuk memulai adalah awal dari segala sesuatu yang hebat.",
    "Kata-kata hari ini, Masa depanmu ditentukan oleh apa yang kamu lakukan hari ini.",
    "Kata-kata hari ini, Kegagalan adalah bagian dari perjalanan menuju sukses.",
    "Kata-kata hari ini, Belajarlah dari setiap kesalahan, dan jadilah lebih baik.",
    "Kata-kata hari ini, Hidup ini penuh dengan kesempatan, jangan sia-siakan.",
    "Kata-kata hari ini, Jangan takut mencoba, karena kegagalan adalah guru terbaik.",
    "Kata-kata hari ini, Hanya mereka yang berani gagal yang bisa meraih kesuksesan besar.",
    "Kata-kata hari ini, Kesuksesan tidak datang kepada mereka yang hanya menunggu.",
    "Kata-kata hari ini, Setiap hari adalah kesempatan baru untuk meraih impianmu.",
    "Kata-kata hari ini, Bersyukurlah untuk setiap tantangan, karena itu membuatmu lebih kuat.",
    "Kata-kata hari ini, Jangan biarkan rasa takut menghentikan langkahmu.",
    "Kata-kata hari ini, Fokuslah pada tujuanmu, bukan pada rintangan yang menghadang.",
    "Kata-kata hari ini, Setiap usaha yang tulus akan membuahkan hasil.",
    "Kata-kata hari ini, Kesuksesan adalah hasil dari persiapan, kerja keras, dan belajar dari kegagalan.",
    "Kata-kata hari ini, Beranilah untuk bermimpi besar dan bekerja keras untuk mencapainya.",
    "Kata-kata hari ini, Ketekunan adalah bahan bakar dari kesuksesan.",
    "Kata-kata hari ini, Tetaplah rendah hati dalam kesuksesan dan kuat dalam kesulitan.",
    "Kata-kata hari ini, Hidup ini tentang perjalanan, bukan tentang tujuan akhir.",
    "Kata-kata hari ini, Jangan pernah berhenti belajar, karena hidup tidak pernah berhenti mengajar.",
    "Kata-kata hari ini, Setiap orang memiliki waktu yang sama, gunakanlah dengan bijak.",
    "Kata-kata hari ini, Kerjakan apa yang bisa kamu kerjakan hari ini, jangan menunggu esok.",
    "Kata-kata hari ini, Impianmu menunggu di sisi lain dari ketakutanmu.",
    "Kata-kata hari ini, Jangan biarkan masa lalu menahanmu dari meraih masa depan.",
    "Kata-kata hari ini, Kamu tidak pernah tahu seberapa dekatnya kesuksesan jika kamu menyerah.",
    "Kata-kata hari ini, Percayalah bahwa kamu bisa, dan kamu sudah setengah jalan ke sana.",
    "Kata-kata hari ini, Kebahagiaan tidak ditemukan di ujung jalan, tapi di sepanjang perjalanan."
];

const kataJorok = ['anjing', 'kontol', 'memek', 'bangsat', 'tai', 'ngentot', 'ngentod', 'babi', 'asu', 'fak', 'fuck', 'puki', 'cuki', 'pepek', 'bokep',
'ktl','ppk','anj','mampus','ewe','bgst','anying','mmk','anjir','ajg','ewean','mamfus','peler','titit','itil','k0nt0l','kuontol',
'k0ntol','kont0l','memeg','memex','muemek','tolol','m3m3k','jembut','jembot'];


module.exports = { kataMotivasi, nama, kataKakGem, kataJorok, emotBinatang };
