const kataMotivasi = [
    "Teruntuk {nama}, ngapain susah-susah? Mending tidur aja.",
    "Teruntuk {nama}, udah lah, nyerah aja. Hidup nggak akan berubah juga.",
    "Teruntuk {nama}, capek-capek buat apa? Nggak ada yang peduli juga.",
    "Teruntuk {nama}, hidup itu ya gini-gini aja. Jangan terlalu berharap.",
    "Teruntuk {nama}, mending rebahan daripada ngurusin mimpi yang nggak kesampaian.",
    "Teruntuk {nama}, buat apa usaha? Hasilnya paling juga biasa-biasa aja.",
    "Teruntuk {nama}, mungkin hari ini nggak akan lebih baik dari kemarin. Nggak usah terlalu semangat.",
    "Teruntuk {nama}, mimpi tinggi-tinggi nanti jatuh lho, mending santai aja.",
    "Teruntuk {nama}, nggak perlu repot-repot, toh nggak ada yang peduli juga.",
    "Teruntuk {nama}, ngapain capek-capek? Toh, hidup cuma sekali, mending nikmatin aja.",
    "Teruntuk {nama}, kenapa harus berjuang? Nanti ujung-ujungnya juga nyesel.",
    "Teruntuk {nama}, buat apa belajar? Toh besok juga lupa.",
    "Teruntuk {nama}, hidup ini udah susah, nggak usah ditambah susah lagi.",
    "Teruntuk {nama}, mending diem aja, daripada bikin masalah.",
    "Teruntuk {nama}, kayaknya rebahan lebih menarik daripada kerja keras.",
    "Teruntuk {nama}, ngapain sih mikir susah-susah? Nggak ada yang peduli juga.",
    "Teruntuk {nama}, nggak usah berharap banyak, biar nggak kecewa.",
    "Teruntuk {nama}, santai aja, yang penting masih bisa makan.",
    "Teruntuk {nama}, ngapain ngikutin mimpi? Toh, kenyataan lebih pahit.",
    "Teruntuk {nama}, kadang yang terbaik adalah nggak ngapa-ngapain.",
    "Teruntuk {nama}, lebih baik diem aja, biar nggak salah langkah.",
    "Teruntuk {nama}, nggak usah muluk-muluk, yang penting hidup aman.",
    "Teruntuk {nama}, buat apa usaha keras? Nanti juga bakal lupa.",
    "Teruntuk {nama}, biarkan hidup berjalan apa adanya, nggak usah berlebihan.",
    "Teruntuk {nama}, mending nyantai, nggak usah terlalu ambisius.",
    "Teruntuk {nama}, jangan terlalu berusaha, nanti capek sendiri.",
    "Teruntuk {nama}, mimpi besar itu capek, lebih baik tidur siang aja.",
    "Teruntuk {nama}, ngapain mikir panjang-panjang? Toh, hasilnya juga sama aja.",
    "Teruntuk {nama}, kadang berhenti itu solusi terbaik.",
    "Teruntuk {nama}, buat apa mikir keras? Toh, besok juga udah beda lagi.",
    "Teruntuk {nama}, nggak usah ngeluh, tapi juga nggak usah terlalu berusaha.",
    "Teruntuk {nama}, yang penting hidup jalan terus, nggak usah terlalu muluk.",
    "Teruntuk {nama}, mending nggak usah berbuat apa-apa, daripada salah.",
    "Teruntuk {nama}, hidup itu udah susah, mending dinikmatin aja.",
    "Teruntuk {nama}, nggak usah terlalu semangat, biar nggak kecewa.",
    "Teruntuk {nama}, mending diem aja, biar nggak salah langkah.",
    "Teruntuk {nama}, ngapain sih mikir susah-susah? Toh, hasilnya juga nggak jauh beda.",
    "Teruntuk {nama}, nggak usah berharap banyak, biar nggak terlalu sakit hati.",
    "Teruntuk {nama}, mending rebahan, biar nggak terlalu capek.",
    "Teruntuk {nama}, lebih baik santai aja, yang penting hidup jalan terus.",
    "Teruntuk {nama}, buat apa susah-susah? Nggak ada yang peduli juga.",
    "Teruntuk {nama}, kadang yang terbaik adalah nggak ngapa-ngapain.",
    "Teruntuk {nama}, ngapain berusaha keras? Toh, hidup cuma sekali."
];

const nama = [
    "Adam", "Ade", "Upho", "Bunga", "Ainun", "Madun", "Bagus", "Bayu", "Bintang",
    "Aji", "Endri", "Salim", "Baim", "Ivana", "Jajang", "Irul", "Leo", "Ali",
    "Naufal", "Farhan", "Nurul", "Ikbal", "Iza", "Rafi", "Alam", "Rama", "Iky",
    "Timothi", "Yohan", "Doy", "Afari", "Adit", "Very", "Dhea", "Elsa", "Wisnu", "Ammar", "Riska", "Nanda", "Baqir"
];
const kataKakGem = [
    "Kata-kata hari ini, Tetap semangat, perjalanan panjang dimulai dari langkah kecil.",
    "Kata-kata hari ini, Jangan menyerah, kesuksesan membutuhkan ketekunan.",
    "Kata-kata hari ini, Setiap tantangan adalah peluang untuk belajar.",
    "Kata-kata hari ini, Kamu lebih kuat dari yang kamu kira.",
    "Kata-kata hari ini, Mimpi besar dimulai dari usaha kecil.",
    "Kata-kata hari ini, Keberhasilan adalah hasil dari kerja keras dan dedikasi.",
    "Kata-kata hari ini, Hari ini adalah kesempatan untuk menjadi lebih baik dari kemarin.",
    "Kata-kata hari ini, Berani mencoba adalah awal dari kesuksesan.",
    "Kata-kata hari ini, Kegagalan adalah batu loncatan menuju keberhasilan.",
    "Kata-kata hari ini, Setiap hari adalah halaman baru dalam kisah hidupmu.",
    "Kata-kata hari ini, Teruslah bergerak maju, langkah kecil pun akan membawa ke tujuan.",
    "Kata-kata hari ini, Peluang besar sering kali tersembunyi di balik tantangan yang sulit.",
    "Kata-kata hari ini, Jadilah versi terbaik dari dirimu setiap hari.",
    "Kata-kata hari ini, Waktu tidak akan menunggu, manfaatkan setiap detiknya.",
    "Kata-kata hari ini, Kesuksesan tidak datang dengan sendirinya, tapi dengan usaha yang tak kenal lelah.",
    "Kata-kata hari ini, Setiap orang sukses pernah gagal, yang penting adalah bangkit lagi.",
    "Kata-kata hari ini, Bekerjalah dengan hati, hasilnya akan mengikuti.",
    "Kata-kata hari ini, Percayalah pada proses, hasilnya akan datang.",
    "Kata-kata hari ini, Setiap langkah yang diambil, sejauh apapun itu, mendekatkanmu ke tujuan.",
    "Kata-kata hari ini, Tidak ada yang mustahil jika kamu memiliki tekad yang kuat.",
    "Kata-kata hari ini, Kesabaran dan ketekunan adalah kunci keberhasilan.",
    "Kata-kata hari ini, Tidak ada yang mudah, tapi semua bisa dicapai dengan kerja keras.",
    "Kata-kata hari ini, Berpikir positif adalah langkah pertama menuju sukses.",
    "Kata-kata hari ini, Keberanian untuk memulai adalah awal dari segala sesuatu yang hebat.",
    "Kata-kata hari ini, Masa depanmu ditentukan oleh apa yang kamu lakukan hari ini.",
    "Kata-kata hari ini, Kegagalan adalah bagian dari perjalanan menuju sukses.",
    "Kata-kata hari ini, Belajarlah dari setiap kesalahan, dan jadilah lebih baik.",
    "Kata-kata hari ini, Hidup ini penuh dengan kesempatan, jangan sia-siakan.",
    "Kata-kata hari ini, Jangan takut mencoba, karena kegagalan adalah guru terbaik.",
    "Kata-kata hari ini, Hanya mereka yang berani gagal yang bisa meraih kesuksesan besar.",
    "Kata-kata hari ini, Kesuksesan tidak datang kepada mereka yang hanya menunggu.",
    "Kata-kata hari ini, Setiap hari adalah kesempatan baru untuk meraih impianmu.",
    "Kata-kata hari ini, Bersyukurlah untuk setiap tantangan, karena itu membuatmu lebih kuat.",
    "Kata-kata hari ini, Jangan biarkan rasa takut menghentikan langkahmu.",
    "Kata-kata hari ini, Fokuslah pada tujuanmu, bukan pada rintangan yang menghadang.",
    "Kata-kata hari ini, Setiap usaha yang tulus akan membuahkan hasil.",
    "Kata-kata hari ini, Kesuksesan adalah hasil dari persiapan, kerja keras, dan belajar dari kegagalan.",
    "Kata-kata hari ini, Beranilah untuk bermimpi besar dan bekerja keras untuk mencapainya.",
    "Kata-kata hari ini, Ketekunan adalah bahan bakar dari kesuksesan.",
    "Kata-kata hari ini, Tetaplah rendah hati dalam kesuksesan dan kuat dalam kesulitan.",
    "Kata-kata hari ini, Hidup ini tentang perjalanan, bukan tentang tujuan akhir.",
    "Kata-kata hari ini, Jangan pernah berhenti belajar, karena hidup tidak pernah berhenti mengajar.",
    "Kata-kata hari ini, Setiap orang memiliki waktu yang sama, gunakanlah dengan bijak.",
    "Kata-kata hari ini, Kerjakan apa yang bisa kamu kerjakan hari ini, jangan menunggu esok.",
    "Kata-kata hari ini, Impianmu menunggu di sisi lain dari ketakutanmu.",
    "Kata-kata hari ini, Jangan biarkan masa lalu menahanmu dari meraih masa depan.",
    "Kata-kata hari ini, Kamu tidak pernah tahu seberapa dekatnya kesuksesan jika kamu menyerah.",
    "Kata-kata hari ini, Percayalah bahwa kamu bisa, dan kamu sudah setengah jalan ke sana.",
    "Kata-kata hari ini, Kebahagiaan tidak ditemukan di ujung jalan, tapi di sepanjang perjalanan."
];


module.exports = { kataMotivasi, nama, kataKakGem };
